### ISSUE TITLE
Recipe seed data isnt working

### ISSUE THREAD

**Issue by AaronMulgrew** [DMU-CTEC2902/TeamTwistedFlax#14]
#3 I know it's to do with the foreign key restraint for UserId, I should be able to fix this today.

**Comment by AaronMulgrew** [comment]
@MariamBajahzar @NjoadAlghanim @Gufraan786  Can you confirm that it's working on your end before I close this issue.
Thanks.

**Comment by Gufraan786** [comment]
@AaronMulgrew Fixed my database errors.
Thanks.

**Comment by AaronMulgrew** [comment]
Ok I will close this issue soon.



On Mon, May 2, 2016 at 7:08 AM -0700, "Gufraan Arkate" <notifications@github.com<mailto:notifications@github.com>> wrote:


@AaronMulgrew<https://github.com/AaronMulgrew> Fixed my database errors.
Thanks.

-
