### ISSUE TITLE
Create Users

### ISSUE THREAD

**Issue by DaveGerrardDMU** [DMU-CTEC2902/TeamTwistedFlax#2]
The website needs the following types of user to support all the functionality:

1. An Author, who writes the recipes.
2. A Reader, who adds comments and suggests changes to recipes.
3. An Adminstrator, who has the power to edit and delete recipes and comments, and block users who misbehave.

**Comment by DaveGerrardDMU** [comment]
@AaronMulgrew if you work through the lab notes about setting up ASP.Net MVC projects, you'll see that the 'full' MVC project type has a lot of stuff built in about user accounts etc. 

Don't think this means you get out of doing loads of work, though! We want all user contributions to be public, so each user is going to have a page that lists all the recipes, long comments and notes they make. So still A LOT for you to do, and you'll have to work closely with @NjoadAlghanim and @MariamBajahzar to get it working.

**Comment by DaveGerrardDMU** [comment]
@AaronMulgrew if you check the Wiki, you can see I put the class diagram I started yesterday in. I hope we can manage users with the UserType enumeration that's in the design, and then use that to work out which bits of the system users are allowed to view / use etc? We might have to get our heads together about that after Easter, though feel free to either send me mails, or even better, add comments to this issue so we can work out how to get that working?

**Comment by AaronMulgrew** [comment]
Hi @DaveGerrardDMU , Thanks for the comment. Since you mentioned the enumeration idea yesterday I have looked online and this looks a good idea, as I was struggling to think of a way to incorporate the User types. I will write further comments when I undoubtedly become stuck!

**Comment by DaveGerrardDMU** [comment]
@AaronMulgrew we need to be careful that enumerations get added to the database properly when you scaffold a class with an enumeration as a property? The documentation suggests it should all be easy, but Microsoft documentation always says that :) So I don't suppose you could run a little test? You don't need to put it in GitHub or anything - just fire up VS2013, start a new project and see what it does whan you scaffold? And also what it does when you add an enumeration later and have to create a Data Migration for it?

**Comment by AaronMulgrew** [comment]
@DaveGerrardDMU  Ok I will do this over the weekend.

**Comment by AaronMulgrew** [comment]
## UserTypes addition
Hi @DaveGerrardDMU, I have done the tests that you have said I should do. Both of the tests worked well. I had to tweak some of the presentation Razor code to correctly show the ability to edit and create the UserTypes, but apart from that it was very successful. Here is the test UserType having been migrated into the database from previously having just a username and password fields. 
![3 datamigrated](https://cloud.githubusercontent.com/assets/16706185/13898683/e87f33b4-edd0-11e5-826d-068aa06f7056.png)

**Comment by AaronMulgrew** [comment]
hi @DaveGerrardDMU, I have thought about my Users stuff tonight, and I've thought that it could be sensible to have some kind of Admin Control panel where you can set the types of certain users to a higher permissions as presumably you would want some way of being able to delegate moderators and administrators, without making the user types visible to the Joe Blogs that would be the standard user. Would this be doable with MVC?

**Comment by DaveGerrardDMU** [comment]
Hi @AaronMulgrew ... Sorry for the slow reply. I haven't had a chance to look at this in depth, but I think the answer might be something to do with things called Role Providers: https://msdn.microsoft.com/en-us/library/8fw7xh74.aspx ?

**Comment by AaronMulgrew** [comment]
@DaveGerrardDMU  
I am going to close this issue as the core functionality now works! I will carry on tagging this issue when doing further commits.
