### ISSUE TITLE
Notes and comments

### ISSUE THREAD

**Issue by DaveGerrardDMU** [DMU-CTEC2902/TeamTwistedFlax#5]
There are two types of comment on the site:

1. Long comments that sit at the foot of each recipe and allow readers to suggest different ways they might cook the recipe, or problems they've had cooking it.
2. Short notes next to each recipe, for users to flag issues like spelling mistakes etc where they've found them.

**Comment by DaveGerrardDMU** [comment]
A thought about how notes will get added - in order to add notes to the side of each recipe in the right place, you might need to break the recipes down a bit, maybe into paragraphs, or perhaps into _instructions_ (which could be another type of class). Then each paragraph / instruction might have one (or many?) notes that go with it? @MariamBajahzar and @NjoadAlghanim probably need to have a talk about this one. :)

**Comment by DaveGerrardDMU** [comment]
@MariamBajahzar the class diagram I did yesterday is now up. I've decided to make things a bit easier by having one Comment class, but using a CommentType enumeration to distinguish between the two. The reason for changing the design like this is because there wasn't enough difference between the two types of comment. Anyway, you'll see from the Yellow Note I put into the diagram that both you and @AaronMulgrew are working on classes that are used throughout the whole rest of the Model, so you'll need to work closely with the other team members on this.

**Comment by AaronMulgrew** [comment]
@MariamBajahzar  Hi mariam, I've changed the comment class slightly as there seemed to be an ICollection in there that I just couldn't understand was in there. Please tell me if that was supposed to be in there.

**Comment by Gufraan786** [comment]
@AaronMulgrew @MariamBajahzar Hi, no the ICollection is not needed in there.

**Comment by AaronMulgrew** [comment]
@Gufraan786 @NjoadAlghanim @MariamBajahzar @DaveGerrardDMU 
Hi guys I have decided to add a view for the comments class, so that would be much better. Is this all ok with you guys? (Sorry dave if you are getting spammed with our comments).

**Comment by Gufraan786** [comment]
@AaronMulgrew Yes, that's fine mate!

**Comment by MariamBajahzar** [comment]
Hi Aaron yes no problem i was thinking of doing it

**Comment by AaronMulgrew** [comment]
@Gufraan786  cool thanks. I think the implementation will be easier just setting it up as a full view rather than partial view business. Certainly helps as it can 'link' from my profile page too.

**Comment by MariamBajahzar** [comment]
@AaronMulgrew  can you please inform me when you push it because i have to change my code thanks

**Comment by AaronMulgrew** [comment]
Already done. Sorry

Sent from Outlook Mobile<https://aka.ms/blhgte>



On Fri, Apr 29, 2016 at 10:55 AM -0700, "MariamBajahzar" <notifications@github.com<mailto:notifications@github.com>> wrote:


@AaronMulgrew<https://github.com/AaronMulgrew> can you please inform me when you push it because i have to change my code thanks

-

**Comment by AaronMulgrew** [comment]
@DaveGerrardDMU  @MariamBajahzar  Hi I've changed the model slightly as Comments ideally need a RecipeId and if I do it this way you can have comments on recipes and also ingredients.

**Comment by AaronMulgrew** [comment]
I think this issue can be safely closed as comments and notes now work properly as expected.
