### ISSUE TITLE
Display comments on profile page

### ISSUE THREAD

**Issue by AaronMulgrew** [DMU-CTEC2902/TeamTwistedFlax#9]
I am hoping to get this completed by Thursday, to get the comments IEnumerable to be displayed on the profile page.

**Comment by Gufraan786** [comment]
Hi Aaron, me and Mariam have realised a small issue regarding when users are not logged in. If you click on the 'Recipe' page and you are not logged in, you can edit content.

**Comment by AaronMulgrew** [comment]
Hi gufraan, this fine they are small issues along with the user profile not working when on home etc. I will fix them today.

**Comment by Gufraan786** [comment]
Thanks mate :)

**Comment by AaronMulgrew** [comment]
@Gufraan786  Gufraan, I will make them visible so Recipe's can be seen, but cannot edit them.

**Comment by Gufraan786** [comment]
Hi Aaron, I was going to suggest that too, great idea!
